name: docker-tools

on:
  push:
    branches: main
    paths:
      - 'Dockerfile*'
      - '.github/workflows/main.yml'
  schedule:
    - cron: '21 3 * * 0' # weekly build

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Publish (ubuntu2204)
      run: |
        registry="moabukar"
        tag="tools:ubuntu2204"
        docker build . -f Dockerfile.ubuntu2204 -t ${registry}/${tag}
        docker push ${registry}/${tag}

    - name: Build and Publish (ubuntu2004)
      run: |
        registry="moabukar"
        tag="tools:ubuntu2004"
        docker build . -f Dockerfile.ubuntu2004 -t ${registry}/${tag}
        docker push ${registry}/${tag}

    - name: Build and Publish (ubuntu1804)
      run: |
        registry="moabukar"
        tag="tools:ubuntu1804"
        docker build . -f Dockerfile.ubuntu1804 -t ${registry}/${tag}
        docker push ${registry}/${tag}

    - name: Build and Publish (alpine)
      run: |
        registry="moabukar"
        tag="tools:alpine"
        docker build . -f Dockerfile.alpine -t ${registry}/${tag}
        docker push ${registry}/${tag}

